# This is a basic workflow to help you get started with Actions

name: Build, Package, and Deploy

# Controls when the action will run. Triggers the workflow on push
# events but only for the develop branch
on:
  push:
    tags:
      - v*
    branches:
      - 0.2.44-entity-caching

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      ## Checkout current branch (the develop branch at this case)
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      ## Setup node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'

      ## Install dependencies
      - name: npm install
        run: |
          npm install
      ## Test
      - name: Package
        run: |
          npm run package
      ## Deploy to github package repo
      - name: Deploy
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
